[build-system]
requires = [
    "setuptools",
    "numpy",
    "Cython",
    "scikit-learn"
]
build-backend = "setuptools.build_meta"

[project]
name = "integration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "category-encoders==2.6.3",
    "cython>=3.2.3",
    "duckdb==1.0.0",
    "loguru>=0.7.3",
    "numpy==1.26.4",
    "onnx==1.14.1",
    "onnxruntime==1.16.3",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.11",
    "pymonetdb==1.8.1",
    "pytest>=9.0.1",
    "scikit-learn==1.5.1",
    "setuptools>=80.9.0",
    "sqlparse>=0.5.3",
]
